development:
  adapter: postgresql
  database: receipt_dev
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: receipt_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: receipt_prod
  pool: 5
  timeout: 5000