# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7280e1e6468823da95caabc7900286ee65a306dbd32236619770d803147b4121b84abb0116ac2fb3cb7ccb7df89f3d470f8c07569d3c71699259b0c393cb4e3c

test:
  secret_key_base: e0b4479fddad9f6ddf8cc952ed5185f78788359805270baf1a569587a18b923cf6ea54a7266c9208ff5b9ffc9c986b76ac68df049b5e6e060a84f2720d38f350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
